name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Déclenche le déploiement lors d'un push sur la branche main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Installation des dépendances
        run: npm install

      - name: Build du projet
        run: npm run build

      - name: Upload de l'artefact
        uses: actions/upload-pages-artifact@v3
        with:
          # Si tu utilises Vite, le dossier est 'dist'. 
          # Si tu utilises Create React App (CRA), c'est 'build'.
          path: ./dist 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Déploiement sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4